AWSTemplateFormatVersion: 2010-09-09
Description: >-
  online pong backend
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
    Default: PongOnline
  Env:
    Type: String
    AllowedValues:
      - Dev
      - Test
      - Prod
  ApiKeyExpires:
    Type: Number
    Description: AppSync API key expiration date (in seconds) since epoch
    Default: 1743756531 # 2025-04-04

Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub ${AppName}-Api-${Env}
      AuthenticationType: API_KEY

  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Expires: !Ref ApiKeyExpires

  ForwardMessageDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: !Sub ${AppName}ForwardMessageDataSource${Env}
      Description: message forwarding datasource for subscription
      Type: NONE

  MutationSendData:
    Type: AWS::AppSync::Resolver
    DependsOn: Schema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: sendData
      DataSourceName: !GetAtt ForwardMessageDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      CodeS3Location: ./backend/graphql/forwardMessage.js

  MutationSendHandShake:
    Type: AWS::AppSync::Resolver
    DependsOn: Schema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: sendHandShake
      DataSourceName: !GetAtt ForwardMessageDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      CodeS3Location: ./backend/graphql/forwardMessage.js

  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: ./backend/graphql/schema.graphql

  WebContentBucket:
    Type: AWS::S3::Bucket

  WebContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref WebContentBucket, /*]]
            Condition:
              StringEquals:
                AWS:SourceArn: !Join
                  - ''
                  - - 'arn:aws:cloudfront::'
                    - !Ref 'AWS::AccountId'
                    - ':distribution/'
                    - !Ref CloudFrontDistribution

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebContentBucket.RegionalDomainName
            Id: S3BucketOrigin
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref CloudFrontCachePolicy
          TargetOriginId: S3BucketOrigin
          ViewerProtocolPolicy: https-only
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${WebContentBucket} OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Default cache policy for S3 distribution
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 1
        Name: !Sub ${AppName}-S3DistributionCachePolicy-${Env}
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

Outputs:
  GraphQLApiId:
    Description: Api ID
    Value: !GetAtt GraphQLApi.ApiId
  GraphQLApiEndpoint:
    Description: Api url
    Value: !GetAtt GraphQLApi.GraphQLUrl
  GraphQLApiKey:
    Description: Api key
    Value: !GetAtt GraphQLApiKey.ApiKey
  WebS3BucketName:
    Description: S3 Bucket for hosting web frontend
    Value: !Ref WebContentBucket
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID for hosting web front end
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name for accessing web front end
    Value: !GetAtt CloudFrontDistribution.DomainName
